NOT READY FOR MERGE - Create cmip6-tasmax-monthly-annual-max (no E&A capability)
NASA-IMPACT/veda-config-eic pull request #131
Opened 2024-09-26 15:43 UTC by freitagb

## Why are you creating this Pull Request?

- [Adding Datasets or Stories](?title=Content%3A%20%3Cname%3E&expand=1&template=content.md)
- [Version Release](?title=Deploy%20vX.X.X&expand=1&template=version_release.md)
- [Other](?expand=1&template=default.md)

2024-10-05 07:53 UTC, j08lue requested changes
Reviewed the new dataset:

https://deploy-preview-131--earth-information-center.netlify.app/data-catalog/cmip6-climdex-tasmax-yearly-median

Made a few copy edits. 

Looks good in terms of functionality.

There are a few unrelated changes in this PR. Perhaps this needs to be rebased to a more recent `develop` or so?

2024-10-05 07:53 UTC, j08lue commented on datasets/cmip6-tasmax-monthly-annual-max.data.mdx
> +    * **Data Units:** Degrees Farenheit
```suggestion
    * **Data Units:** Degrees Fahrenheit
```

2024-10-05 07:53 UTC, j08lue commented on datasets/cmip6-tasmax-monthly-annual-max.data.mdx
> +    This dataset provides the Annual Maximum Near-Surface Air Temperature from 1950 - 2100. The projections are provided for the four different SSP standard scenarios ([SSP126, SSP245, SSP370, SSP585
```suggestion
    This dataset provides the Annual Maximum Near-Surface Air Temperature from 1950 - 2100. The projections are provided for the four different SSP standard scenarios ([SSP126, SSP245, SSP370, SSP585](https://www.dkrz.de/en/communication/climate-simulations/cmip6-en/the-ssp-scenarios)). The Annual Maximum Near-Surface Air Temperature serves as an essential metric for assessing and understanding future climate for the different emissions scenarios, and is a valuable tool for climate scientists, researchers, and policymakers. Monitoring and projecting near surface air temperature over time allows for the identification of trends and variations in temperature extremes, which is crucial for understanding the impact of climate change on local and global climates.
```

2024-10-05 07:53 UTC, j08lue commented on datasets/cmip6-tasmax-monthly-annual-max.data.mdx
> +    - **Data Units:** F
```suggestion
    - **Data Units:** °F
```

2024-10-05 07:53 UTC, j08lue commented on datasets/cmip6-tasmax-monthly-annual-max.data.mdx
> +      unit: Days
```suggestion
      unit: °F
```

2024-10-07 21:53 UTC, agurvich approved these changes

2024-10-07 21:53 UTC, merged