[do not merge this yet] Main menu example
NASA-IMPACT/veda-config-eic pull request #24
Opened 2023-11-14 18:32 UTC by hanbyul-here

Introducing `navMainItem`, `navTitle` to tweak main nav. 
Look at https://github.com/NASA-IMPACT/veda-ui/pull/748 for necessary ui change.

2023-11-14 19:36 UTC, j08lue requested changes
According to the [design](https://github.com/NASA-IMPACT/veda-config-eic/issues/8#issuecomment-1802023387), we want to call the page "Visit the Center" for clarification.

2023-11-14 19:36 UTC, j08lue commented on custom-pages/visit/index.mdx
> +navTitle: Visit
```suggestion
navTitle: Visit the Center
```

2023-11-14 19:58 UTC, hanbyul-here commented
I also added google form environment variable to see the full scope of nav, the nav breaks its style between 990 and 1021 px viewport width.
<img width="979" alt="Screen Shot 2023-11-14 at 2 56 45 PM" src="https://github.com/NASA-IMPACT/veda-config-eic/assets/4583806/ddc430c3-09f1-454e-abdd-d38897ec70e8">

2023-11-17 08:19 UTC, j08lue approved these changes
This solution has been approved and looks good to me https://github.com/NASA-IMPACT/veda-config-eic/issues/22#issuecomment-1815918754

2023-11-17 13:44 UTC, closed without merging